### ISSUE TITLE
Crashed when importing existing library

### ISSUE THREAD

**Issue by nogardvfx** [Casvt/Kapowarr#120]
**Description of the bug**

I am not running this in a docker.
I have been importing my existing library.  I was able to do it a few times, but now I no longer can without the program crashing.  I tried lowering the max folders scans from 20 to 5 (and even 1).

**To Reproduce**

1. Go to: Volumes-> Library Import
2. Set "Max folders scanned" to either 20 or 5.
3. Click "Scan"
4. Watching the terminal I can see the program crash out.

**Expected behaviour**
I would expect to get a list of the comics the program will import from my library.

**Version info**
Kapowarr version 	v1.0.0-beta-3
Python version 	3.8.10.final.0
Database version 	14
Database location 	/usr/serverApps/Kapowarr/db/Kapowarr.db
Data folder 	/usr/serverApps/Kapowarr

**Additional context**
This is the error message:

Traceback (most recent call last):
  File "/home/nogardvfx/.local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nogardvfx/.local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nogardvfx/.local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nogardvfx/.local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/serverApps/Kapowarr/frontend/api.py", line 64, in wrapper
    return method(*args, **kwargs)
  File "/usr/serverApps/Kapowarr/frontend/api.py", line 207, in wrapper
    result = method(*args, **kwargs)
  File "/usr/serverApps/Kapowarr/frontend/api.py", line 398, in api_library_import
    result = propose_library_import(limit, only_english)
  File "/usr/serverApps/Kapowarr/backend/library_import.py", line 174, in propose_library_import
    search_results = run(__search_matches(
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/serverApps/Kapowarr/backend/library_import.py", line 37, in __search_matches
    responses = await gather(*tasks)
  File "/usr/serverApps/Kapowarr/backend/comicvine.py", line 597, in search_volumes_async
    return self.__process_search_results(query, results)
  File "/usr/serverApps/Kapowarr/backend/comicvine.py", line 483, in __process_search_results
    results = [self.__format_volume_output(r) for r in results]
  File "/usr/serverApps/Kapowarr/backend/comicvine.py", line 483, in <listcomp>
    results = [self.__format_volume_output(r) for r in results]
  File "/usr/serverApps/Kapowarr/backend/comicvine.py", line 303, in __format_volume_output
    result['volume_number'] = int(volume_result.group(1))
ValueError: invalid literal for int() with base 10: 'i'

**Comment by Casvt** [comment]
There is a CV search result that has the volume number along the lines of `Volume III` (A.K.A. volume 3). Kapowarr supports it for files but I forgot to add it for CV search results.

**Comment by Casvt** [comment]
Fixed. Will be included in next release.

**Comment by nogardvfx** [comment]
Amazing!  Thank you.
