### ISSUE TITLE
[Bug] Error durring scan for library import

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#134]
**Description of the bug**

While attempting to import my library, I got an error.  The import screen hung and didn't show the error, but it was in the console logs

**To Reproduce**

1. Go to 'Library Import'
2. Increase max folders scanned to 100
3. Click Scan

**Screenshots**

![image](https://github.com/Casvt/Kapowarr/assets/2420694/789bff1e-c11f-4e29-81cd-e7c64bd72c1c)

**Version info**

Kapowarr version    v1.0.0-beta-4
Python version	3.8.17.final.0
Database version	17
OS                            Windows 11 Pro
Docker image           [mrcas/kapowarr-alpha:latest](https://github.com/Casvt/Kapowarr/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)

**Additional context**

```python
2024-01-23 16:57:39 [2024-01-23 16:57:39][waitress-0][INFO] Loading library import
2024-01-23 16:57:46 [2024-01-23 16:57:46][waitress-0][ERROR] Exception on /api/libraryimport [GET]
2024-01-23 16:57:46 Traceback (most recent call last):
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
2024-01-23 16:57:46     response = self.full_dispatch_request()
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
2024-01-23 16:57:46     rv = self.handle_user_exception(e)
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
2024-01-23 16:57:46     rv = self.dispatch_request()
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
2024-01-23 16:57:46     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-01-23 16:57:46   File "/app/frontend/api.py", line 65, in wrapper
2024-01-23 16:57:46     return method(*args, **kwargs)
2024-01-23 16:57:46   File "/app/frontend/api.py", line 215, in wrapper
2024-01-23 16:57:46     result = method(*args, **kwargs)
2024-01-23 16:57:46   File "/app/frontend/api.py", line 402, in api_library_import
2024-01-23 16:57:46     result = propose_library_import(
2024-01-23 16:57:46   File "/app/backend/library_import.py", line 180, in propose_library_import
2024-01-23 16:57:46     search_results = run(__search_matches(
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
2024-01-23 16:57:46     return loop.run_until_complete(main)
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
2024-01-23 16:57:46     return future.result()
2024-01-23 16:57:46   File "/app/backend/library_import.py", line 37, in __search_matches
2024-01-23 16:57:46     responses = await gather(*tasks)
2024-01-23 16:57:46   File "/app/backend/comicvine.py", line 643, in search_volumes_async
2024-01-23 16:57:46     return self.__process_search_results(query, results)
2024-01-23 16:57:46   File "/app/backend/comicvine.py", line 529, in __process_search_results
2024-01-23 16:57:46     results = [self.__format_volume_output(r) for r in results]
2024-01-23 16:57:46   File "/app/backend/comicvine.py", line 529, in <listcomp>
2024-01-23 16:57:46     results = [self.__format_volume_output(r) for r in results]
2024-01-23 16:57:46   File "/app/backend/comicvine.py", line 305, in __format_volume_output
2024-01-23 16:57:46     'description': _clean_description(volume_data['description']),
2024-01-23 16:57:46   File "/app/backend/comicvine.py", line 87, in _clean_description
2024-01-23 16:57:46     for el in removed_elements: el.decompose()
2024-01-23 16:57:46   File "/usr/local/lib/python3.8/site-packages/bs4/element.py", line 984, in __getattr__
2024-01-23 16:57:46     raise AttributeError(
2024-01-23 16:57:46 AttributeError: 'NavigableString' object has no attribute 'decompose'
```

**Comment by Casvt** [comment]
Fixed and will be included in the next release. P.S. thank you for properly formatting and styling the error, you're probably the first person ever to do that here :)
