### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by JonOve** [Casvt/Kapowarr#165]
**Description of the bug**

I receive the error "sqlite3.OperationalError: database is locked".
Not sure if it is a relevant error for downloading files from GetComic?

**To Reproduce**

Just check the logs

**Expected behaviour**
I would not xpect this error, however I do not know if it is a relevant error.

**Screenshots**

![image](https://github.com/Casvt/Kapowarr/assets/66490341/c840aeb0-99bc-4a38-bbd6-30e939f4e824)

**Version info**

Kowarr version v1.0.0-beta-4 in docker on a synology nas

**Comment by Casvt** [comment]
There was something downloading in the background probably. It's fixed already. If anything stops working after the error is raised, just restart Kapowarr.

**Comment by JonOve** [comment]
Clear! Many thanks for all your work!

**Comment by DocDrydenn** [comment]
I was getting the same error. Switched over to `mrcas/kapowarr-alpha:latest` and now running into the following:

```
kapowarr  | [21:53:35][INFO] Starting up Kapowarr
kapowarr  | [21:53:35][WARNING] The value for this setting is invalid: service_preference: mega,mediafire,getcomics,getcomics (torrent),wetransfer
kapowarr  | Traceback (most recent call last):
kapowarr  |   File "/app/Kapowarr.py", line 130, in <module>
kapowarr  |     _main()
kapowarr  |   File "/app/Kapowarr.py", line 40, in _main
kapowarr  |     setup_db()
kapowarr  |   File "/app/backend/db.py", line 907, in setup_db
kapowarr  |     migrate_db(current_db_version)
kapowarr  |   File "/app/backend/db.py", line 666, in migrate_db
kapowarr  |     s["service_preference"] = service_preference
kapowarr  |   File "/app/backend/settings.py", line 264, in __setitem__
kapowarr  |     value = self.__check_value(name, value)
kapowarr  |   File "/app/backend/settings.py", line 232, in __check_value
kapowarr  |     raise InvalidSettingValue(key, value)
kapowarr  | backend.custom_exceptions.InvalidSettingValue: service_preference
kapowarr  | [21:53:35][INFO] Migrating database to newer version...
kapowarr  | [21:53:35][INFO] Changing setting: service_preference->mega,mediafire,getcomics,getcomics (torrent),wetransfer
```
Any fix before I restore from backup?

**Comment by Casvt** [comment]
You're migrating too fast. Upgrade to `alpha-26` first. Then upgrade to `latest`.

**Comment by DocDrydenn** [comment]
That's it. Thanks!

**Comment by opicron** [comment]
Im getting this on:

| Key| Value |
|--------|--------|
| Kapowarr version | V1.3.0 |
| Python version | 3.13.12.final.0 |
| Database version | 45 |
| Database location | /app/db/Kapowarr.db |
| Data folder | /app |
| OS | Linux |
| Can run 64bit | true |

```
[22:14:57][ERROR] UNCAUGHT EXCEPTION IN THREAD: database is locked
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1044, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/local/lib/python3.13/threading.py", line 995, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backend/internals/server.py", line 258, in db_thread
    target(*args, **kwargs)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/app/backend/features/download_queue.py", line 101, in __run_download
    PostProcessor.success(download)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/app/backend/features/post_processing.py", line 330, in success
    cls._run_actions(cls.actions_success, download)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    action(download)
    ~~~~~~^^^^^^^^^^
  File "/app/backend/features/post_processing.py", line 44, in remove_from_queue
    get_db().execute(
    ~~~~~~~~~~~~~~~~^
        "DELETE FROM download_queue WHERE id = ?",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (download.id,)
        ^^^^^^^^^^^^^^
    ).connection.commit()
    ^
sqlite3.OperationalError: database is locked

```
