### ISSUE TITLE
Disk I/O error on TrueNAS

### ISSUE THREAD

**Issue by leewiscovitch** [Casvt/Kapowarr#166]
**Description of the bug**

Trying to delete a volume via webgui, getting similar issue to #116

**To Reproduce**

1. Go to 'Volumes'
2. Click on a volume to see details
3. Click the 'Delete' button
4. Click the green `Delete` button in the pop-up
5. Nothing happens on the screen, pop-up still shows (Same behavior if yes/no for 'Delete Folder' option)
6. Check logs and see the following:

```log
2024-07-06 21:54:19.003973-04:00[2024-07-07 01:54:19][waitress-6][INFO] Deleting volume 12 with delete_folder set to False
2024-07-06 21:54:19.009866-04:00[2024-07-07 01:54:19][waitress-6][ERROR] Exception on /api/volumes/12 [DELETE]
2024-07-06 21:54:19.009931-04:00Traceback (most recent call last):
2024-07-06 21:54:19.009988-04:00File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1455, in wsgi_app
2024-07-06 21:54:19.010019-04:00response = self.full_dispatch_request()
2024-07-06 21:54:19.010047-04:00File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 869, in full_dispatch_request
2024-07-06 21:54:19.010075-04:00rv = self.handle_user_exception(e)
2024-07-06 21:54:19.010103-04:00File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
2024-07-06 21:54:19.010146-04:00rv = self.dispatch_request()
2024-07-06 21:54:19.010174-04:00File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
2024-07-06 21:54:19.010201-04:00return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2024-07-06 21:54:19.010229-04:00File "/app/frontend/api.py", line 64, in wrapper
2024-07-06 21:54:19.010271-04:00return method(*args, **kwargs)
2024-07-06 21:54:19.010299-04:00File "/app/frontend/api.py", line 207, in wrapper
2024-07-06 21:54:19.010326-04:00result = method(*args, **kwargs)
2024-07-06 21:54:19.010353-04:00File "/app/frontend/api.py", line 487, in api_volume
2024-07-06 21:54:19.010380-04:00volume.delete(delete_folder=delete_folder)
2024-07-06 21:54:19.010407-04:00File "/app/backend/volumes.py", line 386, in delete
2024-07-06 21:54:19.010450-04:00cursor.execute("DELETE FROM volumes WHERE id = ?", (self.id,))
2024-07-06 21:54:19.010478-04:00sqlite3.OperationalError: disk I/O error
```

**Expected behaviour**

Should just delete the volume

**Screenshots**

N/A

**Version info**

```txt
Kapowarr version	v1.0.0-beta-4
Python version	3.8.17.final.0
Database version	14
Database location	/app/db/Kapowarr.db
Data folder	/app
```

Running this as an app on TrueNAS SCALE (Dragonfish-24.04.1.1) which means it more kubernetes than docker

**Additional context**

* Can add as much as I need
* All perms on persistent volumes have full control
* Noticing some items aren't showing as downloaded when they are
* Also seeing same behavior as #114 (Although I know that has been addressed in 1.0.0 but not released yet)
* Was initially running with 2GB of RAM, retried with 8GB and same behavior
* Tried with second/different SSD and same behavior

**Comment by Casvt** [comment]
Does it happen for all volumes or only for volumes with a large amount of issues? What I'm noticing is that with both issues TrueNAS is in play. I don't know exactly how that changes things, but it seems like TrueNAS is not happy with the big write being done to the database.
