### ISSUE TITLE
CV parsing fails on issue with range as issue number

### ISSUE THREAD

**Issue by BlackRainbowFT** [Casvt/Kapowarr#169]
**Description of the bug**

I added the italian comic Topolino (which has 3570+ issues) and Kapowarr is unable to download the list of issues.
If I retry after an hour or more (in case ComicVine's rate limiting has something to do with it), no additional issue gets added to the list.

**To Reproduce**

1. Add volume > search for "Topolino"
2. Pick "Topolino (1949) from Painini comics (the one with >=3570 issues)
3. Select it from your library
4. (optional) select "Refresh & Scan"

**Version info**

Kapowarr: v1.0.0-beta-4
Python: 3.8.17.final.0
Database: 14

Running in a Docker container.

**Additional context**

Please note that I've 150+ volumes and this is the first time I'm running into this issue.

Here's a copy of the console log when I click "Refresh & Scan" once.

```
[2024-08-01 18:54:04][Task Handler][DEBUG] Running task Refresh And Scan
[2024-08-01 18:54:04][Task Handler][DEBUG] Creating connection <DBConnection; Task Handler; 126536140507872>
[2024-08-01 18:54:04][Task Handler][DEBUG] Fetching volume data for ['1313']
[2024-08-01 18:54:04][Task Handler][DEBUG] Starting new HTTPS connection (1): comicvine.gamespot.com:443
[2024-08-01 18:54:04][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/volumes/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=deck%2Cdescription%2Cid%2Cimage%2Cissues%2Cname%2Cpublisher%2Cstart_year%2Ccount_of_issues&filter=id%3A1313 HTTP/1.1" 200 None
[2024-08-01 18:54:04][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /a/uploads/scale_small/0/77/567240-00001.jpg?format=json&api_key=APIKEYAPIKEYAPIKEY HTTP/1.1" 200 36748
[2024-08-01 18:54:04][Task Handler][DEBUG] Fetching issue data for volumes ['1313']

[2024-08-01 18:54:05][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313 HTTP/1.1" 200 None
[2024-08-01 18:54:05][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=100 HTTP/1.1" 200 None
[2024-08-01 18:54:06][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=200 HTTP/1.1" 200 None
[2024-08-01 18:54:06][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=300 HTTP/1.1" 200 None
[2024-08-01 18:54:07][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=400 HTTP/1.1" 200 None
[2024-08-01 18:54:07][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=500 HTTP/1.1" 200 None
[2024-08-01 18:54:08][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=600 HTTP/1.1" 200 None
[2024-08-01 18:54:08][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=700 HTTP/1.1" 200 None
[2024-08-01 18:54:08][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=800 HTTP/1.1" 200 None
[2024-08-01 18:54:09][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=900 HTTP/1.1" 200 None
[2024-08-01 18:54:09][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1000 HTTP/1.1" 200 None
[2024-08-01 18:54:10][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1100 HTTP/1.1" 200 None
[2024-08-01 18:54:10][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1200 HTTP/1.1" 200 None
[2024-08-01 18:54:11][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1300 HTTP/1.1" 200 None
[2024-08-01 18:54:11][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1400 HTTP/1.1" 200 None
[2024-08-01 18:54:11][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1500 HTTP/1.1" 200 None
[2024-08-01 18:54:12][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1600 HTTP/1.1" 200 None
[2024-08-01 18:54:12][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1700 HTTP/1.1" 200 None
[2024-08-01 18:54:12][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1800 HTTP/1.1" 200 None
[2024-08-01 18:54:13][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=1900 HTTP/1.1" 200 None
[2024-08-01 18:54:13][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2000 HTTP/1.1" 200 None
[2024-08-01 18:54:13][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2100 HTTP/1.1" 200 None
[2024-08-01 18:54:14][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2200 HTTP/1.1" 200 None
[2024-08-01 18:54:14][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2300 HTTP/1.1" 200 None
[2024-08-01 18:54:14][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2400 HTTP/1.1" 200 None
[2024-08-01 18:54:15][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2500 HTTP/1.1" 200 None
[2024-08-01 18:54:15][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2600 HTTP/1.1" 200 None
[2024-08-01 18:54:15][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2700 HTTP/1.1" 200 None
[2024-08-01 18:54:16][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2800 HTTP/1.1" 200 None
[2024-08-01 18:54:16][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=2900 HTTP/1.1" 200 None
[2024-08-01 18:54:16][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3000 HTTP/1.1" 200 None
[2024-08-01 18:54:17][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3100 HTTP/1.1" 200 None
[2024-08-01 18:54:17][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3200 HTTP/1.1" 200 None
[2024-08-01 18:54:17][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3300 HTTP/1.1" 200 None
[2024-08-01 18:54:18][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3400 HTTP/1.1" 200 None
[2024-08-01 18:54:18][Task Handler][DEBUG] https://comicvine.gamespot.com:443 "GET /api/issues/?format=json&api_key=APIKEYAPIKEYAPIKEY&field_list=id%2Cissue_number%2Cname%2Ccover_date%2Cdescription%2Cvolume&filter=volume%3A1313&offset=3500 HTTP/1.1" 200 None
[2024-08-01 18:54:18][Task Handler][ERROR] An error occured while trying to run a task: 
Traceback (most recent call last):
  File "/app/backend/tasks.py", line 265, in __run_task
    result = task.run()
  File "/app/backend/tasks.py", line 176, in run
    refresh_and_scan(self.volume_id)
  File "/app/backend/volumes.py", line 472, in refresh_and_scan
    cursor.executemany("""
sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.
[2024-08-01 18:54:19][Task Handler][DEBUG] Closing connection <DBConnection; Task Handler; 126536140507872>
```

**Comment by Casvt** [comment]
The problem was that the volume has an issue that does not have a number as it's issue number, but instead has a range (`479-480`) as it's issue number. This wasn't handled by Kapowarr. From the commit description:

> Topolino (4050-1313) has an issue that has the issue number `479-480`, which lead to a tuple of calculated issue numbers (which the DB doesn't support). Fixed by using the first float if it's a tuple.

The fix will be included in the next release.
