### ISSUE TITLE
Kapowarr settings reset

### ISSUE THREAD

**Issue by HereForCodeThatsIt** [Casvt/Kapowarr#174]
**Description of the bug**
Every once in a while, all my setup within Kapowarr will reset. This includes my imported library, monitored series, comicvine api, root folder, any settings i've changed, password. As if I have just installed the app and not set anything up yet.

**To Reproduce**

1. I'm not exactly sure how to reproduce it. I'll set it up one day and then a few days later I'll go on and it will be reset. I do restart the docker container sometimes but I do that for other containers within the stack and they're fine.

**Expected behaviour**
Not to reset over and over again

**Screenshots**

**Version info**

Kapowarr version v1.0.0-beta-4
OS: Running in Docker on Ubuntu 24.04
**Additional context**

**Comment by Casvt** [comment]
Have you set up a Docker volume or folder mapping for the database folder?

**Comment by HereForCodeThatsIt** [comment]
I'm an idiot lol I didn't do that, seems to be working so far

**Comment by HereForCodeThatsIt** [comment]
However I am getting an error now, sorry for the formatting but I will paste the logs below. The first download downloaded fine but is now stuck at 100% "importing".

[2024-08-19 12:01:07][Task Handler][ERROR] An error occured while trying to run a task: 
Traceback (most recent call last):
  File "/app/backend/tasks.py", line 265, in __run_task
    result = task.run()
  File "/app/backend/tasks.py", line 199, in run
    refresh_and_scan()
  File "/app/backend/volumes.py", line 529, in refresh_and_scan
    scan_files(Volume(volume[0]).get_info())
  File "/app/backend/files.py", line 630, in scan_files
    file_id = _add_file(file)
  File "/app/backend/files.py", line 472, in _add_file
    cursor.execute(
sqlite3.OperationalError: database is locked
[2024-08-19 12:01:09][Task Handler][INFO] Finished task Update All
[2024-08-19 12:01:09][Task Handler][INFO] Finished task Update All
[2024-08-19 12:01:09][Task Handler][ERROR] An error occured while trying to run a task: 
Traceback (most recent call last):
  File "/app/backend/tasks.py", line 265, in __run_task
    result = task.run()
  File "/app/backend/tasks.py", line 199, in run
    refresh_and_scan()
  File "/app/backend/volumes.py", line 529, in refresh_and_scan
    scan_files(Volume(volume[0]).get_info())
  File "/app/backend/files.py", line 630, in scan_files
    file_id = _add_file(file)
  File "/app/backend/files.py", line 472, in _add_file
    cursor.execute(
sqlite3.OperationalError: database is locked

**Comment by Casvt** [comment]
It's pretty much fixed at this point, haven't encountered it in a long time.
