### ISSUE TITLE
Error when manually or automatically searching for issue

### ISSUE THREAD

**Issue by brandonlee781** [Casvt/Kapowarr#19]
**Description of the bug**
```

[2023-05-25 00:13:47][Task Handler][DEBUG] Starting new HTTPS connection (1): getcomics.org:443

[2023-05-25 00:13:48][Task Handler][DEBUG] https://getcomics.org:443 "GET /?s=Guardians+of+the+Galaxy+%2318 HTTP/1.1" 200 None

[2023-05-25 00:13:48][Task Handler][DEBUG] Using selector: EpollSelector

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: Guardians Of The Galaxy #18 (2021)

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: {'series': 'Guardians Of The Galaxy', 'year': 2021, 'volume_number': None, 'special_version': None, 'issue_number': 18.0, 'annual': False}

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: Marvel Universe Guardians of the Galaxy #18 (2017)

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: {'series': 'Marvel Universe Guardians of the Galaxy', 'year': 2017, 'volume_number': None, 'special_version': None, 'issue_number': 18.0, 'annual': False}

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: Guardians of the Galaxy #18 (2017)

[2023-05-25 00:13:48][Task Handler][DEBUG] Extracting filename data: {'series': 'Guardians of the Galaxy', 'year': 2017, 'volume_number': None, 'special_version': None, 'issue_number': 18.0, 'annual': False}

[2023-05-25 00:13:48][Task Handler][DEBUG] Matching titles (Guardians of the Galaxy, Guardians Of The Galaxy): True

[2023-05-25 00:13:48][Task Handler][DEBUG] Matching titles (Guardians of the Galaxy, Marvel Universe Guardians of the Galaxy): False

[2023-05-25 00:13:48][Task Handler][DEBUG] Matching titles (Guardians of the Galaxy, Guardians of the Galaxy): True

[2023-05-25 00:13:48][Task Handler][ERROR] An error occured while trying to run a task: 

Traceback (most recent call last):

  File "/app/backend/tasks.py", line 293, in __run_task

    result = task.run()

  File "/app/backend/tasks.py", line 110, in run

    results = auto_search(self.volume_id, self.issue_id)

  File "/app/backend/search.py", line 443, in auto_search

    manual_search(volume_id, issue_id)

  File "/app/backend/search.py", line 349, in manual_search

    result.update(_check_match(result, title, volume_number, issue_numbers, calculated_issue_number, year))

  File "/app/backend/search.py", line 119, in _check_match

    or (isinstance(result['issue_number'], float) and issue_numbers.get(result['issue_number'][0]) == result['year'])

TypeError: 'float' object is not subscriptable
```

**To Reproduce**
Add a volume
Go into volume
Click either search button to search for it

**Version info**

Kapowarr version v1.0.0-beta-1
Python Version 3.8.16.final.0
Database version 6

**Comment by Casvt** [comment]
Fixed in [477c423](https://github.com/Casvt/Kapowarr/commit/477c423aa9ad58c9c9102df67fa85c163981c48f). Will be included in next release
