### ISSUE TITLE
Database location not set when using multiprocessing

### ISSUE THREAD

**Issue by SeanOMik** [Casvt/Kapowarr#219]
**Description of the bug**

Recently, some comics I've tried to download get stuck on the "Importing" status at 100%. I checked logs and saw this:
```
[22:50:06][ERROR] An error occured while trying to run a task:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ~~~~^^^^^^^^^^^^^^^
  File "/app/backend/helpers.py", line 488, in pool_map_func
    return func(value)
  File "/app/backend/volumes.py", line 1171, in map_scan_files
    return scan_files(*a)
  File "/app/backend/volumes.py", line 1005, in scan_files
    volume_data = volume.get_keys((
        'id', 'volume_number', 'year',
        'folder', 'root_folder',
        'special_version'
    ))
  File "/app/backend/volumes.py", line 809, in get_keys
    data = self._get_keys(keys)
  File "/app/backend/volumes.py", line 403, in _get_keys
    get_db(dict).execute(
    ~~~~~~~~~~~~~~~~~~~~^
        f"SELECT {','.join(keys)} FROM volumes WHERE id = ? LIMIT 1;",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        (self.id,)
        ^^^^^^^^^^
    ).fetchone()
    ^
sqlite3.OperationalError: no such table: volumes
"""
```
If I restart kapowarr, the comic issue gets imported, but there's a high chance that the next issue in that series gets stuck as well. The comic series I know that is causing this issue is Radiant Black 2021, but I've had it happen with other series. When the single issue gets stuck, the entire queue gets stuck.

**To Reproduce**

Enable downloading from GetComics and try to import Radiant Black 2021. Wait for it to finish downloading, see that it gets stuck at 100% and importing. Check logs for the sqlite error.

**Expected behavior**

I expect for the issue to import.

**Version info**

Version: v1.0.0
Python version: 3.13.0
Database version: 27

**Comment by Casvt** [comment]
If possible, could you try running Kapowarr with a lower version of Python? Something like 3.10 or 3.8. If it then works, then we now where the problem lies.

**Comment by SeanOMik** [comment]
Sorry, got busy with end of year things and forgot to respond here! Changing python to 3.10 fixed the issue, thanks!

**Comment by SeanOMik** [comment]
Actually, its still happening. This time when trying to download and import "Wolverine: Origins"

**Comment by Casvt** [comment]
Can you do something for me? Go to the file `backend/server.py`, and at the bottom you'll find the `setup_process` function. Please alter the order of the lines so that it goes from this (indentation done with 4 spaces):

```python
def setup_process(log_level: int) -> Callable[[], AppContext]:
    set_db_location()
    setup_logging(do_rollover=False)
    set_log_level(log_level)

    app = Flask(__name__)
    app.teardown_appcontext(close_db)
    return app.app_context
```

To this:

```python
def setup_process(log_level: int) -> Callable[[], AppContext]:
    setup_logging(do_rollover=False)
    set_log_level(log_level)
    set_db_location()

    app = Flask(__name__)
    app.teardown_appcontext(close_db)
    return app.app_context
```

Save the changes. Don't restart the container, if you're using Docker. In the web-UI, go to System -> Status -> Power, and click "Restart". After the application has restarted, set the log level to DEBUG at Settings -> General -> Logging -> Log Level. Then let the error happen. Once it has happened, go to Settings -> General -> Logging, and click "Download Logs". Please share the log file that was downloaded.

**Comment by SeanOMik** [comment]
Here's a log file. I had to delete some issues that I knew were running into the problem when I would download them, that log would have messages as well. After I deleted them, I then redownloaded the same issues and downloaded the log after it got stuck.

[Kapowarr_log_2025_01_27_00_55.txt](https://github.com/user-attachments/files/18552392/Kapowarr_log_2025_01_27_00_55.txt)

**Comment by Casvt** [comment]
The logs don't contain any error, not even the original one. Did it just start working suddenly? Have you upgraded to v1.1.0 in the mean time? If you have a custom image, what is the Dockerfile that builds it? Why do you even use a custom image instead of the default one supplied?

**Comment by SeanOMik** [comment]
It hasn't suddenly started working. The reason I'm using a custom image is because I want the image to be rootless. The one you build isn't rootless. My dockerfile also uses [uv](https://github.com/astral-sh/uv) to compress python binaries, maybe that could be causing an issue, and uses [catatonit](https://github.com/openSUSE/catatonit). 

I just updated the dockerfile for v1.1.0, this is the file. I did comment out copying the server.py file over since that file doesn't seem to exist anymore

```dockerfile
FROM docker.io/library/python:3.10-slim-bullseye
STOPSIGNAL SIGTERM

ARG VERSION=V1.1.0

ENV UMASK="0002" \
    TZ="Etc/UTC"

USER root
WORKDIR /app

RUN apt update && \
    apt install -y \
        bash \
        ca-certificates \
        catatonit \
        curl \
        nano \
        git \
    && \
    git clone https://github.com/Casvt/Kapowarr.git . \
    && if [ -n "${VERSION}" ]; then \
        git checkout "${VERSION}"; \
    fi \
    && \
    pip install uv \
    && \
    uv pip install --system --only-binary=:all: --requirement requirements.txt \
    && apt clean \
    && chown -R root:root /app \
    # allows the container to create sub folders (/app/db, /app/Kapowarr_debug.log, etc.)
    && chmod -R 777 /app \
    && rm -rf \
        /root/.cache \
        /root/.cargo \
        /tmp/*

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod -R 777 /entrypoint.sh

# debug server.py file
#COPY ./backend_server.py /app/backend/server.py
#RUN chmod -R 777 /app/backend/server.py

USER nobody:nogroup
EXPOSE 5656
WORKDIR /data
VOLUME ["/data"]

ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]

LABEL org.opencontainers.image.source="https://github.com/Casvt/Kapowarr.git"
```

This is `entrypoint.sh`:
```sh
#!/usr/bin/env bash

exec \
    /usr/local/bin/python \
        "/app/Kapowarr.py" \
        "--DatabaseFolder" \
        "/data" \
        "$@"
```

---

I just updated the running container to v1.1.0, which didn't fix it. I still see these errors in logs when trying to download and import "Guardians of the Galaxy (2008) Volume 2":
```
[14:33:30][ERROR] UNCAUGHT EXCEPTION IN THREAD: no such table: files
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/app/backend/base/helpers.py", line 700, in pool_map_func
    return func(value)
  File "/app/backend/implementations/conversion.py", line 136, in convert_file
    return converter.converter.convert(converter.file)
  File "/app/backend/implementations/converters.py", line 410, in convert
    zip_file = RARtoZIP.convert(file)[0]
  File "/app/backend/implementations/converters.py", line 284, in convert
    volume_id = FilesDB.volume_of_file(file)
  File "/app/backend/internals/db_models.py", line 92, in volume_of_file
    volume_id = get_db().execute("""
sqlite3.OperationalError: no such table: files
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/backend/features/download_queue.py", line 130, in __run_download
    PostProcesser.success(download)
  File "/app/backend/features/post_processing.py", line 236, in success
    cls._run_actions(cls.actions_success, download)
  File "/app/backend/features/post_processing.py", line 230, in _run_actions
    action(download)
  File "/app/backend/features/post_processing.py", line 117, in convert_file
    mass_convert(
  File "/app/backend/implementations/conversion.py", line 272, in mass_convert
    pool.map(
  File "/app/backend/base/helpers.py", line 765, in map
    return super().map(new_func, new_iterable, chunksize)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
sqlite3.OperationalError: no such table: files
```
I'm not sure where I can make those changes you mentioned earlier in the new v1.1.0 code. 
Is it possible that my database got corrupted somehow? I could also try to strip down my image to ONLY be rootless, none of the other things I do to my image. If that doesn't work, then I'll try your image.

**Comment by Casvt** [comment]
Your database is probably not corrupted, no worries. Please download the zip file below and extract the `server.py` file from it. It has the changes that I suggested applied alongside the general changes from v1.0.0 to v1.1.0. Place this `server.py` file inside the container at `/app/backend/internals/server.py`. Build it and run it until the error comes. Then please share the logs.

So basically do the same thing again, but use the `.py` file downloaded below and put it at `/app/backend/internals/server.py`. 

[server.zip](https://github.com/user-attachments/files/18643166/server.zip)

P.S. All permission and ownership features are coming in v1.2.0.

**Comment by Casvt** [comment]
@SeanOMik you still alive?

**Comment by SeanOMik** [comment]
Sorry, I'm just barely haha! I don't use GitHub much so forgot about this issue. I got the logs for you: [Kapowarr_log_2025_03_29_01_21.txt](https://github.com/user-attachments/files/19514598/Kapowarr_log_2025_03_29_01_21.txt)

It's the same series as the last log, Guardians of the Galaxy (2008) Volume 02. I did a manual search and force overrode the result to make sure it found the right download. Something that may be relevant is that the series was split into two downloads. One zip file for issues 0-14 and another for 15-25.

**Comment by Casvt** [comment]
Oh my god I think I finally found it out. Are you running Kapowarr using a custom database folder via `--DatabaseFolder /path/to/folder`? Because I found a bug in the code that that would cause exactly what you're describing if using a custom folder.

**Comment by SeanOMik** [comment]
Yes I do! I set it to `/data` in the docker image's `entrypoint.sh`.

**Comment by SeanOMik** [comment]
Thanks!! I'll try this out tonight after work!

**Comment by SeanOMik** [comment]
I just tried it out and it did fix the issue! Thanks for being patient with me taking a bit to respond, thanks for this great application! I'll stay on the latest development for now until the next release is made.
