### ISSUE TITLE
error when trying to add "Sonic the hedgehog (1993)" to the library

### ISSUE THREAD

**Issue by ChronoStriker1** [Casvt/Kapowarr#96]
**Description of the bug**
After attempting to add the Series the web interface hangs

**To Reproduce**
1. Search for Sonic the hedgehog
2. click on the title and then add volume button
3. Add volume message stays on the screen

**Expected behaviour**
Series gets added

**Version info**
Kapowarr version	v1.0.0-beta-3
Python version	3.8.17.final.0
Database version	10
Database location	/app/db/Kapowarr.db
Data folder	/app
OS: Unraid 6.12.4 - Kapowarr running in docker container
Browser: Arc, Opera, Chrome

**Additional context**
Error as retrieved from Dozzle:
`10/09/2023
2:17:18 PM
[2023-10-09 14:17:18][waitress-7][ERROR] Exception on /api/volumes [POST]
10/09/2023
2:17:18 PM
Traceback (most recent call last):
10/09/2023
2:17:18 PM
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
10/09/2023
2:17:18 PM
    response = self.full_dispatch_request()
10/09/2023
2:17:18 PM
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
10/09/2023
2:17:18 PM
    rv = self.handle_user_exception(e)
10/09/2023
2:17:18 PM
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
10/09/2023
2:17:18 PM
    rv = self.dispatch_request()
10/09/2023
2:17:18 PM
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
10/09/2023
2:17:18 PM
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
10/09/2023
2:17:18 PM
  File "/app/frontend/api.py", line 55, in wrapper
10/09/2023
2:17:18 PM
    return method(*args, **kwargs)
10/09/2023
2:17:18 PM
  File "/app/frontend/api.py", line 172, in wrapper
10/09/2023
2:17:18 PM
    result = method(*args, **kwargs)
10/09/2023
2:17:18 PM
  File "/app/frontend/api.py", line 390, in api_volumes
10/09/2023
2:17:18 PM
    volume_id = library.add(comicvine_id, root_folder_id, monitor, volume_folder)
10/09/2023
2:17:18 PM
  File "/app/backend/volumes.py", line 632, in add
10/09/2023
2:17:18 PM
    volume_data = ComicVine().fetch_volume(comicvine_id)
10/09/2023
2:17:18 PM
  File "/app/backend/comicvine.py", line 250, in fetch_volume
10/09/2023
2:17:18 PM
    self.__format_issue_output(issue)
10/09/2023
2:17:18 PM
  File "/app/backend/comicvine.py", line 196, in __format_issue_output
10/09/2023
2:17:18 PM
    'calculated_issue_number': process_issue_number(issue_data['issue_number']),
10/09/2023
2:17:18 PM
  File "/app/backend/files.py", line 123, in process_issue_number
10/09/2023
2:17:18 PM
    return _calc_float_issue_number(issue_number)
10/09/2023
2:17:18 PM
  File "/app/backend/files.py", line 97, in _calc_float_issue_number
10/09/2023
2:17:18 PM
    return float(converted_issue_number)
10/09/2023
2:17:18 PM
ValueError: could not convert string to float: '.'`

**Comment by Casvt** [comment]
Which sonic the hedgehog volume exactly? Can you give the CV id or link?

**Comment by ChronoStriker1** [comment]
cv:4050-11074

**Comment by Casvt** [comment]
Fixed in 8be08d7c80dd4c935bed4b16ac18b30c46330551
