### ISSUE TITLE
Issue:  Error when attempting to add volume with 0 issues

### ISSUE THREAD

**Issue by JaredVanderford** [Casvt/Kapowarr#99]
**Description of the bug**
Add errors out when adding a volume with 0 issues.

**To Reproduce**
1. Go to 'Volumes'
2. Click on 'Add Volume'
3. Search for a volume with 0 issues (ex. week of Oct 31st, Supergirl Special (2023)). 
4. Select volume
5. Click 'Add Volume'
6.  See the add window spinning indefinetly.
7.  Observe callstack below in console
 ```[ERROR] Exception on /api/volumes [POST]
2023-10-31 12:30:26 Traceback (most recent call last):
2023-10-31 12:30:26   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
2023-10-31 12:30:26     response = self.full_dispatch_request()
2023-10-31 12:30:26   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
2023-10-31 12:30:26     rv = self.handle_user_exception(e)
2023-10-31 12:30:26   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
2023-10-31 12:30:26     rv = self.dispatch_request()
2023-10-31 12:30:26   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
2023-10-31 12:30:26     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-10-31 12:30:26   File "/app/frontend/api.py", line 55, in wrapper
2023-10-31 12:30:26     return method(*args, **kwargs)
2023-10-31 12:30:26   File "/app/frontend/api.py", line 172, in wrapper
2023-10-31 12:30:26     result = method(*args, **kwargs)
2023-10-31 12:30:26   File "/app/frontend/api.py", line 390, in api_volumes
2023-10-31 12:30:26     volume_id = library.add(comicvine_id, root_folder_id, monitor, volume_folder)
2023-10-31 12:30:26   File "/app/backend/volumes.py", line 640, in add
2023-10-31 12:30:26     volume_data['issues'][0]['title']
2023-10-31 12:30:26 IndexError: list index out of range
```

**Expected behaviour**
Volume is added to collection for future updating and scanning.

**Version info**
Kapowarr version  | v1.0.0-beta-3
Python Version | 3.8.17.final.0
Database Version | 10
OS version | Windows 11
Browser | Brave 1.59.120 Chromium: 118.0.5993.88

**Comment by JaredVanderford** [comment]
Dug into the code a bit to see if I could help.  Looks like this is already solved in the dev branch, just not in the latest release.

**Comment by Casvt** [comment]
No there would still be an error, just not in the same place. Probably some errors in other places too.

[These if statements](https://github.com/Casvt/Kapowarr/blob/development/backend/volumes.py#L43C1-L47C27) would error out for example.

**Comment by Casvt** [comment]
Can you find any other volume that has no issues? The ones that you shared now have one now, so I can't test with them anymore.

**Comment by JaredVanderford** [comment]
Sorry, just saw this comment today.  Unfortunately it's hard to find cases, usually between Sunday and Tuesday, when the weekly pull lists update to the new week, but before new volumes have their issue one out is when I see it.  The new X-men Blue was that way when I did my check this morning, but since then has the 1st issue added on CV.  I'll try to find one next week.

**Comment by Casvt** [comment]
Thank you

**Comment by JaredVanderford** [comment]
I actually thought to check comic vine to see if I could find one that way.  As of this moment  there are 3 options
Marvel Mutts Infinity Comic
X-Men #140: Facsimile Edition
'1a

The third one might be best to test, looks to be the oldest of the 3 entrys so less likely to have an issue added before you can validate the fix

**Comment by Casvt** [comment]
Thank you I was able to test it and my fixes have worked. It's already available in the current alpha-release and will be included in the next beta-release.
